module.exports = {
    GET_EX: 'GET_EX',
    GET_PROFILE: 'GET_PROFILE',
    SIGNIN: 'SIGNIN',
    GET_SUBJECT: 'GET_SUBJECT',
    GET_STUDENT: 'GET_STUDENT',
    GET_CLASS: "GET_CLASS",
    GET_TEACHER: 'GET_TEACHER',
    GET_EVENT: 'GET_EVENT',
    GET_SCORE: 'GET_SCORE',
    GET_REVENUE: 'GET_REVENUE',
    GET_REVENUEDETAIL: 'GET_REVENUEDETAIL',
    GET_OBJECT:'GET_OBJECT',
    GET_TEACHER_NOTIN:'GET_TEACHER_NOTIN',
    GET_CUSTOMER: 'GET_CUSTOMER',
    GET_CUSTOMERBYID: 'GET_CUSTOMERBYID'
}