module.exports = {
    actExample: require('./actExample'),
    actSignIn: require('./actSignIn'),
    actSubject: require('./actSubject'),
    actStudent: require('./actStudent'),
    actClass: require('./actClass'),
    actTeacher: require('./actTeacher'),
    actEvent: require('./actEvent'),
    actScore: require('./actScore'),
    actRevenue: require('./actRevenue'),
    actRevenueDetail: require('./actRevenueDetail'),
    actTransferMoney: require('./actTransferMoney'),
    actCustomer: require('./actCustomer'),
    actReceiveMoney: require('./actReceiveMoney'),
}