module.exports = {
    'SignIn': require('./SignIn/pSignIn.js').default,
    'StudentManagement': require('./StudentManagement/pStudentManagement.js').default,
    'SubjectManagement': require('./SubjectManagement/pSubjectManagement.js').default,
    'TeacherManagement': require('./TeacherManagement/pTeacherManagement.js').default,
    'EventManagement': require('./EventManagement/pEventManagement.js').default,
    'ClassManagement': require('./ClassManagement/pClassManagement.js').default,
    'ScoreManagement': require('./ScoreManagement/pScoreManagement.js').default,
    'RevenueManagement': require('./RevenueManagement/pRevenueManagement.js').default,
    'RevenueDetailManagement': require('./RevenueManagement/pRevenueDetailManagement.js').default,
    'TransferMoneySameBank': require('./TransferMoneySameBank/pTransferMoneySameBank.js').default,
    'CustomerManagement': require('./CustomerManagement/pCustomerManagement.js').default,
    'ReceiveMoneyBankAccount': require('./ReceiveMoneyBankAccount/pReceiveMoneyBankAccount.js').default,
    'Profile': require('./Profile/pProfile.js').default,
}